from __future__ import annotations

from .base import Agent, AgentContext
from tools.model_runtime import generate


class OllamaMathReasoningAgent(Agent):
    """LLM-backed implementation of the solve_math capability.

    Mathematical truth is not claimed here; the existing deterministic
    verifier remains the authority for semantic verification.
    """

    agent_id = "ollama-math-reasoning"

    def __init__(self, *, model: str, endpoint: str = "http://127.0.0.1:11434/api/generate"):
        self.model = model
        self.endpoint = endpoint

    def run(self, context: AgentContext) -> dict:
        raw_input = str(context.request["input"]).strip()
        prompt = (
            "Solve the following mathematical problem. "
            "Return only the final answer and concise derivation. "
            "Do not use markdown fences.\n\n"
            f"Problem: {raw_input}"
        )
        response = generate(
            prompt,
            endpoint=self.endpoint,
            model=self.model,
            temperature=0.0,
            max_tokens=-1,
            timeout=None,
            think=False,
        )
        text = response.text.strip()
        if not text:
            raise ValueError("Ollama returned an empty final response.")

        return {
            "task_id": context.request["task_id"],
            "agent_id": self.agent_id,
            "status": "completed",
            "result": {
                "problem": raw_input,
                "answer": text,
                "model": response.model,
                "extraction": response.extraction,
            },
            "artifacts": [],
            "claims": [
                "The answer was generated by the configured Ollama model."
            ],
            "evidence": [],
            "verification": {
                "status": "not_run",
                "method": "external_deterministic_verifier",
            },
            "uncertainties": [
                "Model output is not a proof of mathematical correctness."
            ],
            "actions": [{"type": "capability", "name": "solve_math"}],
            "metrics": {
                "model": response.model,
                "thinking_present": response.thinking is not None,
            },
            "provenance": {
                "agent_id": self.agent_id,
                "adapter_version": "0.1",
                "backend": "ollama",
                "model": response.model,
                "endpoint": self.endpoint,
            },
        }
