from __future__ import annotations

import hashlib
from pathlib import Path

from .base import Agent, AgentContext


def _project(x: float, y: float, z: float) -> tuple[float, float]:
    return (360 + 42 * (x - y), 315 + 25 * (x + y) - 18 * z)


class PythonVisualizationAgent(Agent):
    agent_id = "python-visualization"

    def run(self, context: AgentContext) -> dict:
        data = context.request["input"]
        dependency = data["dependencies"]["math"]
        expression = dependency["expression"]
        if expression != "x**2 + y**2":
            raise ValueError("This first reproducible visualization backend supports x**2 + y**2.")

        artifact_dir = Path(context.request["constraints"].get("artifact_dir", "artifacts"))
        artifact_dir.mkdir(parents=True, exist_ok=True)
        svg_path = artifact_dir / "surface-z-x2-y2.svg"

        size = 9
        steps = 18
        grid = []
        for i in range(steps + 1):
            x = -size + 2 * size * i / steps
            row = []
            for j in range(steps + 1):
                y = -size + 2 * size * j / steps
                z = (x * x + y * y) / 8
                row.append(_project(x / 2, y / 2, z))
            grid.append(row)

        lines = [
            " ".join(f"{x:.2f},{y:.2f}" for x, y in row)
            for row in grid
        ]
        columns = [
            " ".join(f"{grid[i][j][0]:.2f},{grid[i][j][1]:.2f}" for i in range(steps + 1))
            for j in range(steps + 1)
        ]

        body = [
            '<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640" viewBox="0 0 720 640">',
            '<rect width="720" height="640" fill="#111"/>',
            '<text x="360" y="36" text-anchor="middle" fill="#fff" font-size="22">z = x² + y²</text>',
            '<text x="360" y="61" text-anchor="middle" fill="#bbb" font-size="13">deterministic SVG generated by Python agent</text>',
        ]
        for points in lines + columns:
            body.append(f'<polyline points="{points}" fill="none" stroke="#7fc8ff" stroke-width="1" opacity="0.62"/>')
        body.extend([
            '<circle cx="360" cy="315" r="4" fill="#fff"/>',
            '<text x="370" y="310" fill="#fff" font-size="12">vertex (0,0,0)</text>',
            "</svg>",
        ])
        svg_path.write_text("\n".join(body), encoding="utf-8")

        raw = svg_path.read_bytes()
        verified = raw.startswith(b"<svg") and raw.rstrip().endswith(b"</svg>") and len(raw) > 1000
        artifact = {
            "path": str(svg_path),
            "type": "image/svg+xml",
            "bytes": len(raw),
            "sha256": hashlib.sha256(raw).hexdigest(),
        }
        return {
            "task_id": context.request["task_id"],
            "agent_id": self.agent_id,
            "status": "completed" if verified else "failed",
            "result": {
                "method": "python_stdlib_svg",
                "expression": expression,
                "projection": "fixed_isometric",
                "grid_size": [steps + 1, steps + 1],
            },
            "artifacts": [artifact],
            "claims": ["A deterministic SVG surface artifact was generated from the math-agent result."],
            "evidence": [{"type": "artifact_integrity", "svg_envelope_valid": verified}],
            "verification": {"status": "passed" if verified else "failed", "method": "svg_integrity"},
            "uncertainties": [],
            "actions": [{"type": "capability", "name": "visualize_math_python"}],
            "metrics": {"surface_points": (steps + 1) ** 2},
            "provenance": {"agent_id": self.agent_id, "adapter_version": "0.3", "backend": "python_stdlib"},
        }
